_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/research/cvl-zhusheng/detectron2/tools/output/model_final.pth"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 3
# This is similar to the setting used in Mask R-CNN paper, Appendix A
# But there are some differences, e.g., we did not initialize the output
# layer using the corresponding classes from COCO
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
DATASETS:
  TRAIN: ("kitti2cityscapes_fine_instance_seg_train",)
  TEST: ("kitti2cityscapes_fine_instance_seg_test",)
SOLVER:
  BASE_LR: 0.01
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 8000
